### ISSUE TITLE
Adding modifier to some param in array item breaks metadata validation

### ISSUE THREAD

**Issue by jacek-jablonski** [bitnami-labs/readme-generator-for-helm#11]
Hi,

it seems like adding modifier to array item key breaks metadata validation. Here is minimal example:

```yaml
## @section Jobs definition

## Jobs definition
##
jobs:
  -
    ## @param jobs[0].nameOverride String to partially override jobs.names.fullname
    ##
    nameOverride: ""
    ## @param jobs[0].fullnameOverride String to fully override jobs.names.fullname
    ##
    fullnameOverride: ""
    ## @param jobs[0].resources.limits The resources limits override for the Job
    ##
    resources:
      limits: {}
```

Above works fine, but generates `undefined` for `jobs[0].resources.limits`:
```
### Jobs definition

| Name                       | Description                                      | Value       |
| -------------------------- | ------------------------------------------------ | ----------- |
| `jobs[0].nameOverride`     | String to partially override jobs.names.fullname | `""`        |
| `jobs[0].fullnameOverride` | String to fully override jobs.names.fullname     | `""`        |
| `jobs[0].resources.limits` | The resources limits override for the Job        | `undefined` |
```

So, lets annotate `jobs[0].resources.limits` with [object] modifier:
```yaml
## @section Jobs definition

## Jobs definition
##
jobs:
  -
    ## @param jobs[0].nameOverride String to partially override jobs.names.fullname
    ##
    nameOverride: ""
    ## @param jobs[0].fullnameOverride String to fully override jobs.names.fullname
    ##
    fullnameOverride: ""
    ## @param jobs[0].resources.limits [object] The resources limits override for the Job
    ##
    resources:
      limits: {}
```

This however breaks metadata validation:
```bash
❯ npx readme-generator -v values2.yaml -r README.md
Skipping check for jobs[0].nameOverride
Skipping check for jobs[0].fullnameOverride
Skipping check for jobs[0].resources.limits
INFO: Checking missing metadata...

######
The following errors must be fixed before proceeding
######

ERROR: Metadata provided for non existing key: jobs[0].nameOverride
ERROR: Metadata provided for non existing key: jobs[0].fullnameOverride
ERROR: Metadata provided for non existing key: jobs[0].resources.limits
ERROR: Wrong metadata!
```

Generally I am trying to document quite a big and complicated array element. Is it a recommended way to do it with `[0]` in parameter's path or is there more generic way?
Thanks.
