### ISSUE TITLE
undefined value for parameters with .dot in the key

### ISSUE THREAD

**Issue by wils0ns** [bitnami-labs/readme-generator-for-helm#22]
Version: readme-generator-for-helm@1.3.0

Example:

```yaml
## @section Testing Parameters
## @param this.works a param that works
## @param t.testing.me nested param with dot not working
this.works: "fine"
t:
  testing.me: 123
```

Renders:

### Testing Parameters

| Name           | Description                       | Value       |
| -------------- | --------------------------------- | ----------- |
| `this.works`   | a param that works                | `fine`      |
| `t.testing.me` | nested param with dot not working | `undefined` |

---
Parameters with dot in their key are not the smartest idea, but it is out their, real life example:

```yaml
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: <accountname>@<GCP-project-name>.iam.gserviceaccount.com
```
