### ISSUE TITLE
Allow values with `null` values during the schema generation

### ISSUE THREAD

**Issue by antgamdia** [bitnami-labs/readme-generator-for-helm#31]
Context: json-schema does not apply any restrictions on the default field, but openapi schema does. Specifically, they say "the value MUST conform to the defined type for the Schema Object".

I assume this is the reason [why this check is there](https://github.com/bitnami-labs/readme-generator-for-helm/blob/main/lib/render.js#L200). However, if the `nullable: true` is passed, the `null` value is allowed. [Spec here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-20). [Issue here](https://github.com/OAI/OpenAPI-Specification/issues/2057)

Shouldn't we just add `nullable: true` when a `null` property is detected?
At least, I don't think we should throw an error.

Example:

```yaml
## @section kubeappsapis parameters
kubeappsapis:
  pluginConfig:
    kappController:
      packages:
        v1alpha1:
          ## @param kubeappsapis.pluginConfig.kappController.packages.v1alpha1.defaultPrereleasesVersionSelection Default policy for allowing prereleases containing one of the identifiers
          ## ref: https://carvel.dev/kapp-controller/docs/latest/package-consumer-concepts/#prereleases
          ## e.g:
          # defaultPrereleasesVersionSelection: 
          # - rc
          defaultPrereleasesVersionSelection: null
```

```js
{
  name: 'kubeappsapis.pluginConfig.kappController.packages.v1alpha1.defaultPrereleasesVersionSelection',
  value: 'null',
  description: 'Default policy for allowing prereleases containing one of the identifiers',
  section: 'kubeappsapis parameters',
  type: 'object',
  nullable: true
}
```
