### ISSUE TITLE
Feature Request: Support Multiple Values Files

### ISSUE THREAD

**Issue by yaskinny** [bitnami-labs/readme-generator-for-helm#49]
Hello!
Is it possible to pass multiple values files?
for instance if I have a chart with multiple values files for different environments, is there a way to use `readme-generator` to add all of them into my README?

an example:
`values.prod.yaml`:
```yaml
## @section general
## @param user username for app
user: this

## @section production
## @param ca_type ca type
ca_type: acme
```
`values.staging.yaml`:
```yaml
## @section general
## @param user username for app
user: this

## @section staging
## @param tls_provider ca type
ca_type: self_signed
```

If its not already possible, it would be very useful if You can add it. I'm using this tool for other stuff too like Ansible roles: `defaults/main.yaml` and `vars/main.yaml`. I believe this feature will add more use cases to this tool.
