### ISSUE TITLE
An empty ## Parameters section in README leads to loss of following section header

### ISSUE THREAD

**Issue by charlesj68** [bitnami-labs/readme-generator-for-helm#72]
Using 2.5.1 I have noticed that if the Parameters section of the README.md is empty then running the generator will consume the following section header in the process of putting the markdown tables in place.

values.yaml
```yaml
## @section Global parameters
global:
  ## @param global.imageRegistry Global Docker image registry
  imageRegistry: ""
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  imagePullSecrets: []
  ## @param global.storageClass Global StorageClass for Persistent Volume(s)
  storageClass: ""
```

Starting README.md
```plain
# Bug demonstration README

Introduction text

## Section 1 Header

Section 1 content

## Parameters

## Section 2 Header

Section 2 content
```

I've built readme-generator 2.5.1 as a docker image, so running that image to process the values.yaml:
```bash
docker run --user 1000:1000     \
        -v "/home/cjones/work/readme-generator-bug":/src \
        readme-generator-for-helm:2.5.1 \
        readme-generator \
        -v "/src/values.yaml" \
        -s "/src/values.schema.json" \
        -r "/src/README.md"
```

I see this output where `## Section 2 Header` is now gone

```plain
# Bug demonstration README

Introduction text

## Section 1 Header

Section 1 content

## Parameters

### Global parameters

| Name                      | Description                                     | Value |
| ------------------------- | ----------------------------------------------- | ----- |
| `global.imageRegistry`    | Global Docker image registry                    | `""`  |
| `global.imagePullSecrets` | Global Docker registry secret names as an array | `[]`  |
| `global.storageClass`     | Global StorageClass for Persistent Volume(s)    | `""`  |


Section 2 content
```
