### ISSUE TITLE
[BUG REPORT] Repeated value in path results in an incorrect default value. 

### ISSUE THREAD

**Issue by HamzaMasood1** [bitnami-labs/readme-generator-for-helm#74]
![image](https://github.com/bitnami-labs/readme-generator-for-helm/assets/47217263/d8403b1b-ba58-4910-964a-87155e1682d7)
As you can see from the above image, since ingress is repeated twice, I get a strange output for the default value, instead of just "/"

![image](https://github.com/bitnami-labs/readme-generator-for-helm/assets/47217263/3268450f-ebfe-487c-8e7f-4a0f9392540a)
As you can see from this image, since ingress is not repeated, I do not get the error. I get the expected output for the default value.

This is the structure of my yaml for the first image(with the bug):
ingress:
   ```yaml
ingress:
    ## @param global.ingress.enabled if true, an ingress resource is deployed. Only useful if an ingress controller is available, like Ingress-NGINX.
    enabled: false
    ## @param global.ingress.className Ingress.className defines the class or configuration of ingress which should be used by the controller
    className: nginx

    annotations:
      ## @param global.ingress.annotations.ingress.kubernetes.io/rewrite-target ingress annoaation for rewrite-target
      ingress.kubernetes.io/rewrite-target: "/"
```
